App:
 Debug: false
 DbLog: false
 LogFile: tmp/run.log

Script:
 Folder: script
 LogFolder: tmp/log

Sqlite:
 DbPath: gonitor.db

HttpServer:
 Host: 127.0.0.1
 Post: 8855

WeCom:
 CorpId: wwe369416f1c4fc21b
 CorpSecret: XCg9b27jgd07960Ym7j9DcdhgehUKnQIfozFnBYTDko
 AgentId: 1000002
